### PR TITLE
chore: update nbconvert version

### LINKED ISSUE #59: nbconvert - Module not found errors
I tried to run on Python 3.10 Kernel in CloudPak - script stopped in step 3 complaining about a missing module: `nbconvert`.

`!pip list` revealed an outdated version of the module (5), so we installed the latest per 2023-07:

```
!pip install --index-url https://pypi.python.org/simple  -U "nbconvert>=7.7.1"
```

This fixed the issues.

### PR DESCRIPTION
**Pull request by haodeqi**
fixes: https://github.com/watson-developer-cloud/assistant-skill-analysis/issues/59

### CODE REVIEW

**Comment by haodeqi** [comment]
hi @rfazeli , can you take a look at this PR when you get a chance. Thank you!

**Comment by rfazeli** [comment]
Thanks for the update @haodeqi. Looks good to me.

**Review by tsinggggg — APPROVED** [review]
Hi @haodeqi , thanks a lot for the PR, this looks good to me.

Some unit tests are failing and also the main branch build has been failing as well(unfortunately the logs are gone), should we at least try re-running it? I saw a time out error so it might be intermittent. But the key error is bit weirder.

**Comment by haodeqi** [comment]
hi @tsinggggg, thanks for checking. The key error looks like a issue with pandas version. The integration test isnt super reliable because we use a dev instance and i would imagine it might get deleted.

**Comment by tsinggggg** [comment]
Hi Haode, thanks for fixing the pandas issue! Looking at the build, it seems we should probably limit numpy version to <1.20.0 as well, just to keep np.int to get the tests run.

**Comment by tsinggggg** [comment]
Thanks for the update Haode! I think I know why the tests are failing..

In the action skill notebook, we renamed the file name variable 
image

but did not rename the regex pattern during testing
image


therefore it's not swapping in the local json file name and just keep the variable as ###

**Pull request merged**
