### PR TITLE
feat: improve multi-thread inference and fix corner case

### PR DESCRIPTION
**Pull request by haodeqi**
- improve multi-thread inference and resolve thread contention issue observed in studio testing.
- minor bug fixes

### CODE REVIEW

**Comment by haodeqi** [comment]
hi @tsinggggg , can you take a look at this PR when you have some time. Thank you!

**Comment by tsinggggg** [comment]
Hi Haode, thanks a lot for the fix, just wondering, would you please elaborate a bit on the thread contention issue you ran into on watson studio? thank you!

**Comment by haodeqi** [comment]
hi @tsinggggg , the resource allocated in studio is quite small. Even setting the number of workers equal to the number of cpus, the inference could still get struck. There is a few improvements. 1. ping the service before actual inference to load the model 2. use executor service/futures with proper timeouts and retries

**Review by tsinggggg — APPROVED** [review]
Thanks a lot for the explanation and fixes, this looks good to me!

**Pull request merged**
