### PR TITLE
feat: refactor and doc update to support dialog in coexistence

### PR DESCRIPTION
**Pull request by haodeqi**
- update all the action skill notebook to support both dialog and action analysis
- update the docs of all of the notebooks and readme
- update utilities to support dialog in coexistence.

### CODE REVIEW

**Comment by haodeqi** [comment]
hi @tsinggggg , can you take a look at this PR when you have some time. Thank you.

**Comment by tsinggggg** [comment]
Hi @haodeqi , thanks a lot for the PR! I think the notebook name needs update here https://github.com/watson-developer-cloud/assistant-skill-analysis/blob/master/tests/end2end/end2end_test.py#L21 for tests to pass. and a few lines below for the action one

**Review by tsinggggg — APPROVED** [review]
Thanks a lot for the PR Haode, I guess the same notebook works for both action and dialog jsons because we have the condition when parsing json... https://github.com/watson-developer-cloud/assistant-skill-analysis/blob/052fd7e131bc72c2be3c1c4a010588890870a5e4/assistant_skill_analysis/utils/skills_util.py#L184

Have you tried it with dialog in new WA? Otherwise this looks good to merge when tests pass. Thank you!

**Comment by tsinggggg** [comment]
Ah somehow I lost write access to this repo...

**Comment by haodeqi** [comment]
hi @tsinggggg , the behavior of the notebook is verified against dialog/action workspace of the new experience.

**Review by rfazeli — APPROVED** [review]
Thanks for the updates, folks! This looks good to me.

**Pull request merged**
